-- ZYLO V1 whole-house schema. Safe for the existing project table: it does not drop it.

create extension if not exists pgcrypto;

create table if not exists public.homes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  overall_style text default 'Modern',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.spaces (
  id uuid primary key default gen_random_uuid(),
  home_id uuid not null references public.homes(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  type text not null,
  target_style text,
  status text not null default 'not designed',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.designs (
  id uuid primary key default gen_random_uuid(),
  home_id uuid not null references public.homes(id) on delete cascade,
  space_id uuid not null references public.spaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  image_path text,
  generated_image_path text,
  detected_style text,
  confidence double precision,
  target_style text,
  prompt text,
  budget_inr numeric default 0,
  recommendations jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  units integer not null default 1,
  metadata jsonb,
  created_at timestamptz not null default now()
);

alter table public.homes enable row level security;
alter table public.spaces enable row level security;
alter table public.designs enable row level security;
alter table public.usage_events enable row level security;

grant select, insert, update, delete on public.homes, public.spaces, public.designs to authenticated;
grant select, insert on public.usage_events to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Recreate policies idempotently.
drop policy if exists "homes_select_own" on public.homes;
drop policy if exists "homes_insert_own" on public.homes;
drop policy if exists "homes_update_own" on public.homes;
drop policy if exists "homes_delete_own" on public.homes;
create policy "homes_select_own" on public.homes for select to authenticated using (auth.uid() = user_id);
create policy "homes_insert_own" on public.homes for insert to authenticated with check (auth.uid() = user_id);
create policy "homes_update_own" on public.homes for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "homes_delete_own" on public.homes for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "spaces_select_own" on public.spaces;
drop policy if exists "spaces_insert_own" on public.spaces;
drop policy if exists "spaces_update_own" on public.spaces;
drop policy if exists "spaces_delete_own" on public.spaces;
create policy "spaces_select_own" on public.spaces for select to authenticated using (auth.uid() = user_id);
create policy "spaces_insert_own" on public.spaces for insert to authenticated with check (auth.uid() = user_id);
create policy "spaces_update_own" on public.spaces for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "spaces_delete_own" on public.spaces for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "designs_select_own" on public.designs;
drop policy if exists "designs_insert_own" on public.designs;
drop policy if exists "designs_update_own" on public.designs;
drop policy if exists "designs_delete_own" on public.designs;
create policy "designs_select_own" on public.designs for select to authenticated using (auth.uid() = user_id);
create policy "designs_insert_own" on public.designs for insert to authenticated with check (auth.uid() = user_id);
create policy "designs_update_own" on public.designs for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "designs_delete_own" on public.designs for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "usage_select_own" on public.usage_events;
drop policy if exists "usage_insert_own" on public.usage_events;
create policy "usage_select_own" on public.usage_events for select to authenticated using (auth.uid() = user_id);
create policy "usage_insert_own" on public.usage_events for insert to authenticated with check (auth.uid() = user_id);

-- Private room image bucket.
insert into storage.buckets (id, name, public)
values ('room-images', 'room-images', false)
on conflict (id) do update set public = false;

drop policy if exists "zylo_room_upload" on storage.objects;
drop policy if exists "zylo_room_select" on storage.objects;
drop policy if exists "zylo_room_update" on storage.objects;
drop policy if exists "zylo_room_delete" on storage.objects;

create policy "zylo_room_upload" on storage.objects for insert to authenticated
with check (bucket_id='room-images' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "zylo_room_select" on storage.objects for select to authenticated
using (bucket_id='room-images' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "zylo_room_update" on storage.objects for update to authenticated
using (bucket_id='room-images' and (storage.foldername(name))[1]=auth.uid()::text)
with check (bucket_id='room-images' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "zylo_room_delete" on storage.objects for delete to authenticated
using (bucket_id='room-images' and (storage.foldername(name))[1]=auth.uid()::text);
