-- ZYLO 2.8: run once in Supabase SQL Editor
create table if not exists public.user_credits (
 user_id uuid primary key references auth.users(id) on delete cascade,
 balance integer not null default 3 check(balance>=0),
 lifetime_purchased integer not null default 0 check(lifetime_purchased>=0),
 lifetime_used integer not null default 0 check(lifetime_used>=0),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.payment_orders (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 razorpay_order_id text not null unique, razorpay_payment_id text unique,
 pack_id text not null, amount_inr integer not null check(amount_inr>=0),
 credits integer not null check(credits>0), status text not null default 'created' check(status in('created','paid','failed')),
 created_at timestamptz not null default now(), paid_at timestamptz
);
alter table public.user_credits enable row level security;
alter table public.payment_orders enable row level security;
drop policy if exists "Users can read own credits" on public.user_credits;
create policy "Users can read own credits" on public.user_credits for select to authenticated using ((select auth.uid())=user_id);
drop policy if exists "Users can read own payment orders" on public.payment_orders;
create policy "Users can read own payment orders" on public.payment_orders for select to authenticated using ((select auth.uid())=user_id);
-- No browser INSERT/UPDATE policies: billing mutations are backend-only.
