"use client";
import Protected from "@/components/Protected";
import Link from "next/link";
import { useEffect,useMemo,useState,use } from "react";
import { supabase } from "@/lib/supabase";

const TYPES=["Living Room","Bedroom","Kitchen","Dining Room","Bathroom","Study / Office","Kids Room","Balcony","Staircase","Entrance / Foyer","Terrace","Garden / Outdoor"];
const STYLES=["Modern","Minimalist","Scandinavian","Industrial","Boho"];
const ICON={"Living Room":"🛋️","Bedroom":"🛏️","Kitchen":"🍳","Dining Room":"🍽️","Bathroom":"🚿","Study / Office":"🧑‍💻","Kids Room":"🧸","Balcony":"🌿","Staircase":"🪜","Entrance / Foyer":"🚪","Terrace":"🏡","Garden / Outdoor":"🌳"};
function guess(v){const n=v.trim().toLowerCase();if(n.includes("balcony"))return"Balcony";if(n.includes("kitchen"))return"Kitchen";if(n.includes("living")||n.includes("hall"))return"Living Room";if(n.includes("dining"))return"Dining Room";if(n.includes("bath")||n.includes("toilet"))return"Bathroom";if(n.includes("study")||n.includes("office"))return"Study / Office";if(n.includes("kids")||n.includes("child"))return"Kids Room";if(n.includes("stair"))return"Staircase";if(n.includes("foyer")||n.includes("entrance"))return"Entrance / Foyer";if(n.includes("terrace")||n.includes("rooftop"))return"Terrace";if(n.includes("garden")||n.includes("outdoor")||n.includes("yard"))return"Garden / Outdoor";if(n.includes("bed"))return"Bedroom";return null}

function HomeDetail({id}){
 const [home,setHome]=useState(null),[spaces,setSpaces]=useState([]),[type,setType]=useState(TYPES[0]),[name,setName]=useState(""),[theme,setTheme]=useState("Modern"),[error,setError]=useState(""),[notice,setNotice]=useState(""),[adding,setAdding]=useState(false),[savingTheme,setSavingTheme]=useState(false);
 async function load(){setError("");const [{data:h,error:e},{data:s,error:se}]=await Promise.all([supabase.from("homes").select("*").eq("id",id).single(),supabase.from("spaces").select("*").eq("home_id",id).order("created_at")]);if(e){setError(e.message);return}if(se){setError(se.message);return}setHome(h);setTheme(h.overall_style||"Modern");setSpaces(s||[])}
 useEffect(()=>{load()},[id]);
 const suggested=useMemo(()=>guess(name),[name]);const mismatch=suggested&&suggested!==type?suggested:null;const designed=spaces.filter(s=>s.status==="designed").length;const progress=spaces.length?Math.round(designed/spaces.length*100):0;
 async function addSpace(e){e.preventDefault();if(adding)return;if(mismatch){setError(`The name looks like "${mismatch}" but the selected type is "${type}". Use ${mismatch} or rename the space.`);return}setAdding(true);setError("");setNotice("");const {data:{session}}=await supabase.auth.getSession();const user=session?.user;if(!user){setError("Please log in again.");setAdding(false);return}const clean=name.trim()||type;const {data,error}=await supabase.from("spaces").insert({home_id:id,user_id:user.id,type,name:clean,target_style:theme,status:"not designed"}).select("*").single();if(error)setError(error.message);else{setName("");setSpaces(c=>[...c,data]);setNotice(`${clean} added as ${type} with the ${theme} house theme.`)}setAdding(false)}
 async function saveTheme(){if(savingTheme)return;setSavingTheme(true);setError("");setNotice("");const {error:e}=await supabase.from("homes").update({overall_style:theme}).eq("id",id);if(e){setError(e.message);setSavingTheme(false);return}const {error:se}=await supabase.from("spaces").update({target_style:theme}).eq("home_id",id).neq("status","designed");setHome(h=>h?{...h,overall_style:theme}:h);setSpaces(c=>c.map(s=>s.status!=="designed"?{...s,target_style:theme}:s));if(se)setError(`House theme saved, but unfinished spaces could not be synchronized: ${se.message}`);else setNotice(`${theme} is now the whole-house theme. Unfinished spaces were synchronized; completed designs were preserved.`);setSavingTheme(false)}
 return <main className="workspace"><div className="workspace-header"><div><div className="eyebrow">Your digital home</div><h1>{home?.name||"Loading home…"}</h1><p className="muted">Design every space separately while keeping one visual language across the house.</p></div><Link href="/dashboard" className="btn secondary">← All homes</Link></div>{error&&<div className="error">{error}</div>}{notice&&<div className="notice">{notice}</div>}
 <div className="card" style={{marginBottom:22}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap"}}><div><div className="eyebrow">Whole-house progress</div><h2>{designed} of {spaces.length} spaces designed</h2><p className="muted">House theme: <strong>{home?.overall_style||theme}</strong></p></div><strong style={{fontSize:28}}>{progress}%</strong></div><div className="progress"><span style={{width:`${progress}%`}}/></div></div>
 <div className="two-col"><div className="card"><h3>Whole-house theme</h3><p className="muted">New and unfinished spaces follow this theme. Completed designs keep their chosen style.</p><div className="field"><select value={theme} onChange={e=>setTheme(e.target.value)}>{STYLES.map(x=><option key={x}>{x}</option>)}</select></div><button className="btn" onClick={saveTheme} disabled={savingTheme}>{savingTheme?"Saving…":"Save & sync house theme"}</button></div>
 <form className="card" onSubmit={addSpace}><h3>Add a space</h3><p className="muted">Choose the real space type first. ZYLO uses it for recommendations and Visual AI.</p><div className="field"><label>Space type</label><select value={type} onChange={e=>{setType(e.target.value);setError("")}}>{TYPES.map(t=><option key={t}>{t}</option>)}</select></div><div className="field"><label>Space name</label><input value={name} onChange={e=>{setName(e.target.value);setError("")}} placeholder={`Example: ${type}`}/></div>{mismatch&&<div className="notice"><strong>Check the space type.</strong><p>You typed a name that looks like <strong>{mismatch}</strong>, but selected <strong>{type}</strong>.</p><button type="button" className="btn secondary" onClick={()=>{setType(mismatch);setNotice(`Space type changed to ${mismatch}.`)}}>Use {mismatch}</button></div>}<button className="btn" disabled={adding||!!mismatch}>{adding?"Adding…":"+ Add space"}</button></form></div>
 <h2 style={{marginTop:34}}>Spaces</h2><div className="grid">{spaces.map(s=><Link className="card" href={`/space/${s.id}`} key={s.id}><div className="space-icon">{ICON[s.type]||"🏠"}</div><h3>{s.name}</h3><p className="muted">{s.type} · {s.target_style||theme}</p><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><span className="tag">{s.status==="designed"?"✓ Designed":"Not designed"}</span><span className="tag">{s.target_style===home?.overall_style?"House theme":"Custom style"}</span></div><p className="muted">Design this space →</p></Link>)}</div></main>
}
export default function Page({params}){const {id}=use(params);return <Protected><HomeDetail id={id}/></Protected>}
