"use client";
import Protected from "@/components/Protected";
import Link from "next/link";
import { useEffect, useState, use } from "react";
import { supabase } from "@/lib/supabase";

const types=["Living Room","Bedroom","Kitchen","Dining Room","Bathroom","Study / Office","Kids Room","Balcony","Staircase","Entrance / Foyer","Terrace","Garden / Outdoor"];
const icon={"Living Room":"🛋️","Bedroom":"🛏️","Kitchen":"🍳","Dining Room":"🍽️","Bathroom":"🚿","Study / Office":"🧑‍💻","Kids Room":"🧸","Balcony":"🌿","Staircase":"🪜","Entrance / Foyer":"🚪","Terrace":"🏡","Garden / Outdoor":"🌳"};
function HomeDetail({id}){
 const [home,setHome]=useState(null);const [spaces,setSpaces]=useState([]);const [type,setType]=useState(types[0]);const [name,setName]=useState("");const [theme,setTheme]=useState("Modern");const [error,setError]=useState("");const [adding,setAdding]=useState(false);const [savingTheme,setSavingTheme]=useState(false);
 async function load(){setError("");const [{data:h,error:e},{data:s,error:se}]=await Promise.all([supabase.from("homes").select("*").eq("id",id).single(),supabase.from("spaces").select("*").eq("home_id",id).order("created_at")]);if(e){setError(e.message);return;}if(se){setError(se.message);return;}setHome(h);setTheme(h.overall_style||"Modern");setSpaces(s||[])}
 useEffect(()=>{load()},[id]);
 async function addSpace(e){e.preventDefault();if(adding)return;setAdding(true);setError("");const {data:{session}}=await supabase.auth.getSession();const user=session?.user;if(!user){setError("Please log in again.");setAdding(false);return;}const cleanName=name.trim()||type;const {data,error}=await supabase.from("spaces").insert({home_id:id,user_id:user.id,type,name:cleanName,target_style:theme}).select("*").single();if(error)setError(error.message);else{setName("");setSpaces(current=>[...current,data])}setAdding(false)}
 async function saveTheme(){if(savingTheme)return;setSavingTheme(true);setError("");const previous=home;setHome(h=>h?{...h,overall_style:theme}:h);const {error}=await supabase.from("homes").update({overall_style:theme}).eq("id",id);if(error){setHome(previous);setError(error.message)}setSavingTheme(false)}
 return <main className="workspace"><div className="workspace-header"><div><div className="eyebrow">Your digital home</div><h1>{home?.name||"Loading home…"}</h1><p className="muted">Design spaces separately while keeping one visual language across the house.</p></div><Link href="/dashboard" className="btn secondary">← All homes</Link></div>{error&&<div className="error">{error}</div>}<div className="two-col"><div className="card"><h3>Whole-house theme</h3><p className="muted">This acts as the default design direction for new spaces.</p><div className="field"><select value={theme} onChange={e=>setTheme(e.target.value)}>{["Modern","Minimalist","Scandinavian","Industrial","Boho"].map(x=><option key={x}>{x}</option>)}</select></div><button className="btn" onClick={saveTheme} disabled={savingTheme}>{savingTheme?"Saving…":"Save house theme"}</button></div><form className="card" onSubmit={addSpace}><h3>Add a space</h3><div className="field"><select value={type} onChange={e=>setType(e.target.value)}>{types.map(t=><option key={t}>{t}</option>)}</select></div><div className="field"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Optional name: Master Bedroom" /></div><button className="btn" disabled={adding}>{adding?"Adding…":"+ Add space"}</button></form></div><h2 style={{marginTop:34}}>Spaces</h2><div className="grid">{spaces.map(s=><Link className="card" href={`/space/${s.id}`} key={s.id}><div className="space-icon">{icon[s.type]||"🏠"}</div><h3>{s.name}</h3><p className="muted">{s.type}</p><span className="tag">Design this space →</span></Link>)}</div></main>
}
export default function Page({params}){const {id}=use(params);return <Protected><HomeDetail id={id}/></Protected>}
